apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "threadwatch.fullname" . }}-threads
  labels:
    {{- include "threadwatch.labels" . | nindent 4 }}
data:
  threads.yaml: |
    threads:
{{- range .Values.config.threads }}
      - label: {{ .label | quote }}
        owner: {{ .owner | quote }}
        repo: {{ .repo | quote }}
        number: {{ .number }}
{{- end }}
